<div class="overflow-hidden">
    <div class="vh-100 overflow-auto">
        <form wire:submit.prevent="submitInquiry">
            <div class="container" style="margin-top: 7%;">
                <div class="row mb-2">

                    <div class="col-12">
                        <div class="d-flex align-items-start">
                            @if($property->images && count($property->images) > 0)
                            <img src="{{ asset('storage/' . $property->images[0]) }}"
                                class="rounded-3 me-2"
                                style="width: 100px; height: 100px; object-fit: cover;">
                            @endif
                            <div class="">
                                <p class="fw-medium fs-5 mb-0">{{ $property->propertyName }} Inquire</p>
                                <p class="mt-0"><small>{{ $property->address }}</small></p>
                                <p><small>₱{{ number_format($property->propertyCost, 2) }} monthly</small></p>
                            </div>
                        </div>

                        <div class="row">
                            <!-- Calendar Section -->
                            <div class="col-6">
                                <!-- Calendar -->
                                <div class="calendar-wrapper border rounded-3 p-2 mb-3">
                                    <div class="d-flex justify-content-between align-items-center mb-2">
                                        <button type="button" class="btn btn-sm btn-link text-dark p-1" id="prevMonth">
                                            <i class="bi bi-chevron-left"></i>
                                        </button>
                                        <h6 class="mb-0 fw-semibold" style="font-size: 14px;" id="currentMonth"></h6>
                                        <button type="button" class="btn btn-sm btn-link text-dark p-1" id="nextMonth">
                                            <i class="bi bi-chevron-right"></i>
                                        </button>
                                    </div>

                                    <div class="calendar-grid">
                                        <div class="calendar-header">
                                            <div class="calendar-day-header">Su</div>
                                            <div class="calendar-day-header">Mo</div>
                                            <div class="calendar-day-header">Tu</div>
                                            <div class="calendar-day-header">We</div>
                                            <div class="calendar-day-header">Th</div>
                                            <div class="calendar-day-header">Fr</div>
                                            <div class="calendar-day-header">Sa</div>
                                        </div>
                                        <div class="calendar-dates" id="calendarDates"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <!-- Time Slots -->
                                <div class="time-slots-wrapper">
                                    <h6 class="fw-semibold mb-2 small">Available Times</h6>
                                    <div class="time-slots-grid" id="timeSlots">
                                        <!-- Time slots will be generated by JavaScript -->
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="">
                            <button
                                class="btn btn-sm btn-outline-dark fw-medium"
                                type="button"
                                wire:click="cancel"
                                wire:loading.attr="disabled">
                                <small>Cancel</small>
                            </button>

                            <button
                                class="btn btn-sm btn-dark fw-medium"
                                wire:loading.attr="disabled"
                                id="submitBtn">
                                <span wire:loading.remove wire:target="submitInquiry">
                                    <small>Send Inquiry Request</small>
                                </span>
                                <span wire:loading wire:target="submitInquiry">
                                    <small>Sending <span class="loading-dots"></span></small>
                                </span>
                            </button>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="d-flex align-items-start mb-4">
                            <div class="me-3">
                                @if($property->user->profile_image)
                                <img src="{{ asset('storage/' . $property->user->profile_image) }}"
                                    class="rounded-circle border"
                                    style="width: 100px; height: 100px; object-fit: cover;">
                                @else
                                <div class="rounded-circle bg-dark text-white d-flex align-items-center justify-content-center border"
                                    style="width: 100px; height: 100px; object-fit: cover;">
                                    {{ strtoupper(substr($property->user->firstName, 0, 1)) }}
                                </div>
                                @endif
                            </div>
                            <div class="">
                                <p class="fw-medium fs-5 mb-0">{{ $property->user->firstName }} {{ $property->user->lastName }}</p>
                                <span class="badge rounded-pill mt-0" style="background-color: #dcfce7; color: #166534; font-size: 11px; font-weight: 600; padding: 6px 12px;">
                                    <i class="fas fa-check-circle me-1" style="font-size: 10px;"></i>
                                    Verified Host
                                </span>

                                <p class="mt-3"><small>Property Host</small></p>
                            </div>
                        </div>

                        <!-- Message Section -->
                        <div class="mt-4">
                            <x-floating-labels.text-area
                                id="message"
                                height="150"
                                label="Send a message to the host."
                                wire:model="message" />
                        </div>

                        <!-- Hidden input to store the datetime for Livewire -->
                        <input type="hidden" id="preferredVisitDate" wire:model="preferredVisitDate">
                    </div>
                </div>
            </div>
        </form>

    </div>
    <!-- Toast Notifications -->
    @if(session('success'))
    <div class="position-fixed top-0 end-0 p-3" style="z-index: 9999;">
        <div class="toast show align-items-center text-white bg-success border-0" role="alert">
            <div class="d-flex">
                <div class="toast-body">
                    <i class="bi bi-check-circle-fill me-2"></i>
                    {{ session('success') }}
                </div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button>
            </div>
        </div>
    </div>
    @endif

    @if(session('error'))
    <div class="position-fixed top-0 end-0 p-3" style="z-index: 9999;">
        <div class="toast show align-items-center text-white bg-danger border-0" role="alert">
            <div class="d-flex">
                <div class="toast-body">
                    <i class="bi bi-exclamation-triangle-fill me-2"></i>
                    {{ session('error') }}
                </div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button>
            </div>
        </div>
    </div>
    @endif


    <style>
        .hover-opacity:hover {
            opacity: 0.7;
            transition: opacity 0.2s;
        }

        .selected-datetime-card {
            background-color: #f8f9fa;
        }

        .calendar-wrapper {
            background: white;
        }

        .calendar-grid {
            display: grid;
            gap: 3px;
        }

        .calendar-header {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 3px;
            margin-bottom: 3px;
        }

        .calendar-day-header {
            text-align: center;
            font-size: 10px;
            font-weight: 600;
            color: #6c757d;
            padding: 2px 0;
        }

        .calendar-dates {
            display: grid;
            grid-template-columns: repeat(9, 1fr);
            gap: 3px;
        }

        .calendar-date {
            aspect-ratio: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 6px;
            cursor: pointer;
            font-size: 11px;
            transition: all 0.2s ease;
            border: 1px solid transparent;
            padding: 2px;
        }

        .calendar-date:not(.disabled):not(.other-month):hover {
            background-color: #e7f3ff;
            border-color: #0d6efd;
        }

        .calendar-date.selected {
            background-color: #0d6efd;
            color: white;
            font-weight: 600;
        }

        .calendar-date.today {
            border: 1.5px solid #0d6efd;
            font-weight: 600;
        }

        .calendar-date.disabled {
            color: #dee2e6;
            cursor: not-allowed;
        }

        .calendar-date.other-month {
            color: #adb5bd;
        }

        .time-slots-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            max-height: 280px;
            overflow-y: auto;
            padding-right: 5px;
        }

        .time-slot {
            padding: 12px;
            border: 1px solid #dee2e6;
            border-radius: 8px;
            text-align: center;
            cursor: pointer;
            transition: all 0.2s ease;
            font-size: 14px;
            font-weight: 500;
        }

        .time-slot:hover {
            border-color: #0d6efd;
            background-color: #e7f3ff;
        }

        .time-slot.selected {
            background-color: #0d6efd;
            color: white;
            border-color: #0d6efd;
        }

        .time-slot.disabled {
            opacity: 0.4;
            cursor: not-allowed;
            background-color: #f8f9fa;
        }

        .time-slots-grid::-webkit-scrollbar {
            width: 6px;
        }

        .time-slots-grid::-webkit-scrollbar-track {
            background: #f1f1f1;
            border-radius: 10px;
        }

        .time-slots-grid::-webkit-scrollbar-thumb {
            background: #888;
            border-radius: 10px;
        }

        .time-slots-grid::-webkit-scrollbar-thumb:hover {
            background: #555;
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            let selectedDate = null;
            let selectedTime = null;
            let currentMonth = new Date();
            currentMonth.setDate(1);

            const monthNames = ["January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"
            ];

            // Time slots (8 AM to 5 PM, hourly)
            const timeSlots = [
                '8:00 AM', '9:00 AM', '10:00 AM', '11:00 AM',
                '12:00 PM', '1:00 PM', '2:00 PM', '3:00 PM',
                '4:00 PM', '5:00 PM'
            ];

            function renderCalendar() {
                const year = currentMonth.getFullYear();
                const month = currentMonth.getMonth();

                document.getElementById('currentMonth').textContent = `${monthNames[month]} ${year}`;

                const firstDay = new Date(year, month, 1).getDay();
                const daysInMonth = new Date(year, month + 1, 0).getDate();
                const daysInPrevMonth = new Date(year, month, 0).getDate();

                const calendarDates = document.getElementById('calendarDates');
                calendarDates.innerHTML = '';

                const today = new Date();
                today.setHours(0, 0, 0, 0);

                // Previous month days
                for (let i = firstDay - 1; i >= 0; i--) {
                    const date = daysInPrevMonth - i;
                    const dateElement = createDateElement(date, true, false);
                    calendarDates.appendChild(dateElement);
                }

                // Current month days
                for (let date = 1; date <= daysInMonth; date++) {
                    const currentDate = new Date(year, month, date);
                    const isPast = currentDate < today;
                    const isToday = currentDate.getTime() === today.getTime();

                    const dateElement = createDateElement(date, false, isPast, isToday, currentDate);
                    calendarDates.appendChild(dateElement);
                }

                // Next month days
                const totalCells = calendarDates.children.length;
                const remainingCells = 42 - totalCells; // 6 rows * 7 days
                for (let date = 1; date <= remainingCells; date++) {
                    const dateElement = createDateElement(date, true, false);
                    calendarDates.appendChild(dateElement);
                }
            }

            function createDateElement(date, isOtherMonth, isDisabled, isToday = false, fullDate = null) {
                const div = document.createElement('div');
                div.className = 'calendar-date';
                div.textContent = date;

                if (isOtherMonth) {
                    div.classList.add('other-month');
                }

                if (isDisabled) {
                    div.classList.add('disabled');
                }

                if (isToday) {
                    div.classList.add('today');
                }

                if (selectedDate && fullDate && selectedDate.getTime() === fullDate.getTime()) {
                    div.classList.add('selected');
                }

                if (!isOtherMonth && !isDisabled && fullDate) {
                    div.addEventListener('click', function() {
                        selectDate(fullDate);
                    });
                }

                return div;
            }

            function selectDate(date) {
                selectedDate = date;
                renderCalendar();
                renderTimeSlots();
                updateHiddenInput();
            }

            function renderTimeSlots() {
                const timeSlotsContainer = document.getElementById('timeSlots');
                timeSlotsContainer.innerHTML = '';

                timeSlots.forEach(time => {
                    const slot = document.createElement('div');
                    slot.className = 'time-slot';
                    slot.textContent = time;

                    if (selectedTime === time) {
                        slot.classList.add('selected');
                    }

                    slot.addEventListener('click', function() {
                        if (selectedDate) {
                            selectTime(time);
                        }
                    });

                    timeSlotsContainer.appendChild(slot);
                });
            }

            function selectTime(time) {
                selectedTime = time;
                renderTimeSlots();
                updateHiddenInput();
            }

            function updateHiddenInput() {
                if (selectedDate && selectedTime) {
                    // Convert to datetime-local format
                    const year = selectedDate.getFullYear();
                    const month = String(selectedDate.getMonth() + 1).padStart(2, '0');
                    const day = String(selectedDate.getDate()).padStart(2, '0');

                    // Parse time
                    let [time, period] = selectedTime.split(' ');
                    let [hours, minutes] = time.split(':');
                    hours = parseInt(hours);

                    if (period === 'PM' && hours !== 12) {
                        hours += 12;
                    } else if (period === 'AM' && hours === 12) {
                        hours = 0;
                    }

                    const formattedHours = String(hours).padStart(2, '0');
                    const dateTimeValue = `${year}-${month}-${day}T${formattedHours}:${minutes || '00'}`;

                    document.getElementById('preferredVisitDate').value = dateTimeValue;

                    // Trigger Livewire update
                    const event = new Event('input', {
                        bubbles: true
                    });
                    document.getElementById('preferredVisitDate').dispatchEvent(event);
                }
            }

            // Month navigation
            document.getElementById('prevMonth').addEventListener('click', function() {
                currentMonth.setMonth(currentMonth.getMonth() - 1);
                renderCalendar();
            });

            document.getElementById('nextMonth').addEventListener('click', function() {
                currentMonth.setMonth(currentMonth.getMonth() + 1);
                renderCalendar();
            });

            // Initialize
            renderCalendar();
            renderTimeSlots();

            // Auto-hide toasts after 5 seconds
            const toasts = document.querySelectorAll('.toast');
            toasts.forEach(toast => {
                setTimeout(() => {
                    toast.classList.remove('show');
                }, 5000);
            });

            // Validate before submit
            document.getElementById('submitBtn').addEventListener('click', function(e) {
                if (!selectedDate || !selectedTime) {
                    e.preventDefault();
                    alert('Please select both a date and time for your visit.');
                }
            });
        });
    </script>
</div>